import{a as v,S as M,i as m}from"./assets/vendor-Db2TdIkw.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const n of a.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function s(e){if(e.ep)return;e.ep=!0;const a=r(e);fetch(e.href,a)}})();const P="49649354-b54131589ae558e3bfeef2cb6",$="https://pixabay.com/api/",x=15;async function y(o,t=1){try{return(await v.get($,{params:{key:P,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:x}})).data}catch{throw new Error("Ошибка при загрузке изображений")}}const h=document.querySelector(".gallery");let B=new M(".gallery a",{captionsData:"alt",captionDelay:250});function g(o){const t=o.map(({webformatURL:r,largeImageURL:s,tags:e,likes:a,views:n,comments:S,downloads:q})=>`
            <li class="item">
                <a href="${s}" class="gallery-link">
                    <img src="${r}" alt="${e}" class="gallery-image">
                </a>
                <div class="info">
                    <p><b>Likes:</b> ${a}</p>
                    <p><b>Views:</b> ${n}</p>
                    <p><b>Comments:</b> ${S}</p>
                    <p><b>Downloads:</b> ${q}</p>
                </div>
            </li>
            `).join("");h.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){h.innerHTML=""}function p(){document.querySelector(".loader").classList.remove("hidden")}function b(){document.querySelector(".loader").classList.add("hidden")}function L(){document.querySelector(".load-more").classList.remove("hidden")}function c(){document.querySelector(".load-more").classList.add("hidden")}function d(o){m.info({message:o})}function w(o){m.error({message:o})}const I=document.querySelector(".form"),O=document.querySelector(".load-more"),D=document.querySelector(".gallery");let u="",l=1,i=0,f=0;I.addEventListener("submit",async o=>{o.preventDefault();const t=o.target.elements["search-text"].value.trim();if(!t){d("Please enter a search term!");return}u=t,l=1,i=0,E(),c(),p();try{const r=await y(u,l);f=r.totalHits,r.hits.length===0?d("Sorry, no images found for your query."):(g(r.hits),i+=r.hits.length,i<f&&L())}catch{w("Failed to load images. Try again later.")}finally{b()}});O.addEventListener("click",async o=>{o.preventDefault(),l+=1,c(),p();try{const t=await y(u,l);g(t.hits),i+=t.hits.length,lightbox.refresh();const r=D.querySelector(".gallery-item");if(r){const s=r.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}i>=f?(d("We're sorry, but you've reached the end of search results."),c()):L()}catch{w("Failed to load more images.")}finally{b()}});
//# sourceMappingURL=index.js.map
